"""
intent_golden.py — The held-out novel-phrasings set for the intent parser.

Phase 0 of the hybrid semantic intent layer (docs/hybrid-semantic-intent-layer.md,
§7): a set of REALISTIC requests for each intent, phrased in ways the current
regex patterns never anticipated. Each query carries the intent a user would
expect it to resolve to. This is the ONLY intent-level ground truth in the
codebase (golden.py is a merchant-*matching* benchmark and carries zero intent
labels), so it doubles as the ongoing intent golden set: extended over time
from approved Phase B exemplars, kept separate from golden.py's merchant set.

NOVELTY CONTRACT — enforced by scripts/phase0_baseline.py at run time:
    For each entry, the EXPECTED intent must NOT be reachable by a raw regex
    match (only the offline ~semantic/~fuzzy fallback or nothing). A query
    that literally contains one of its intent's pattern phrases measures
    nothing — Tier 1 already handles it, so it must be replaced. The harness
    fails loudly on any violation.

PRIVACY: this file contains only request phrasing — no merchant contact data,
no real identifiers — so it is safe to commit (unlike golden.py's emails).

Conventions:
    query   the request exactly as a user might type it (mixed case ok)
    intent  the expected intent, one of INTENT_KEYWORDS (or "segment")
    note    why this phrasing is novel / what it probes (optional)
"""

# Queries use key merchants (MEDPLUS, SPAR, ADDIDE, LAGOON WATERS, ...) and
# file segments ("the NNPC file") so the requests read exactly like ops
# language — the same phrasings the Rule Engine's pattern mining would learn
# from real usage if users actually typed them.
INTENT_GOLDEN = [
    # ── static_account ────────────────────────────────────────────────────
    {"query": "who handles the money for MEDPLUS",
     "intent": "static_account",
     "note": "no 'static account' / 'beneficiary' / 'payable' wording at all"},
    {"query": "where does the payout for LAGOON WATERS land",
     "intent": "static_account",
     "note": "payout phrasing; none of the static_account regexes fire"},
    {"query": "which account do we settle ADDIDE into",
     "intent": "static_account",
     "note": "'settle' is close to settlement, but no pattern word appears"},
    {"query": "the recipient details for MONEYTRUST",
     "intent": "static_account",
     "note": "'recipient' instead of 'beneficiary'"},
    {"query": "who gets paid for SPAR's sales",
     "intent": "static_account",
     "note": "'gets paid' is settlement language; no pattern word"},
    {"query": "where do the funds for ARTEE INDUSTRIES flow into",
     "intent": "static_account",
     "note": "'funds flow into' — no static/beneficiary/payable wording"},
    {"query": "which account do we remit RUBELS' takings into",
     "intent": "static_account",
     "note": "'remit takings' — settlement phrasing, no pattern word"},
    {"query": "the money landing account for BOKKU MART",
     "intent": "static_account",
     "note": "'money landing account' — no 'static account' phrase"},

    # ── tid ───────────────────────────────────────────────────────────────
    {"query": "the device ids for LAGOON WATERS",
     "intent": "tid",
     "note": "'device ids' never appears in tid patterns"},
    {"query": "what terminals does SPAR operate",
     "intent": "tid",
     "note": "bare 'terminals' — patterns require 'terminal id' or 'tids'"},
    {"query": "list the pos machines for MEDPLUS",
     "intent": "tid",
     "note": "'pos machines' is terminal language, no regex word"},
    {"query": "the machine codes for GAJI TAIWO",
     "intent": "tid",
     "note": "'machine codes' — device language, no 'tid'/'terminal id'"},
    {"query": "which POS gadgets belong to WSV VENTURES",
     "intent": "tid",
     "note": "'POS gadgets' — terminal language, no pattern word"},
    {"query": "every device registered to BOKKU MART",
     "intent": "tid",
     "note": "'device registered' — no 'tid'/'terminal' pattern"},

    # ── mxcode ────────────────────────────────────────────────────────────
    {"query": "what is the merchant identifier for MEDPLUS",
     "intent": "mxcode",
     "note": "'identifier' vs pattern 'merchant code'"},
    {"query": "the mx reference for LAGOON WATERS",
     "intent": "mxcode",
     "note": "'mx reference' — pattern needs 'mx code'/'mxcode'"},
    {"query": "which code identifies SHOPRITE in the system",
     "intent": "mxcode",
     "note": "verb 'identifies' carries the meaning"},
    {"query": "what code is ORIENT AFRICA filed under",
     "intent": "mxcode",
     "note": "'filed under' — no 'mx code'/'merchant code' phrase"},
    {"query": "the system reference for ADDIDE",
     "intent": "mxcode",
     "note": "'system reference' instead of 'merchant code'"},
    {"query": "the lookup key for LAGOON WATERS in the parameter file",
     "intent": "mxcode",
     "note": "'lookup key' — identifier language, no pattern word"},

    # ── email ─────────────────────────────────────────────────────────────
    {"query": "the official mail of BEACONHEALTH",
     "intent": "email",
     "note": "bare 'mail' — pattern requires e-mail/email/emails"},
    {"query": "get the mail for SHOPRITE",
     "intent": "email",
     "note": "'mail' without the leading e misses every email regex"},
    {"query": "the inbox for BEACONHEALTH",
     "intent": "email",
     "note": "'inbox' — no 'email'/'e-mail' token"},
    {"query": "where do we send MEDPLUS' statements",
     "intent": "email",
     "note": "'send statements' — correspondence language, no 'email'"},
    {"query": "the mail drop for ADDIDE",
     "intent": "email",
     "note": "'mail drop' — bare 'mail' phrasing, no pattern word"},

    # ── phone ─────────────────────────────────────────────────────────────
    {"query": "how do I reach LAGOON WATERS",
     "intent": "phone",
     "note": "'reach' is contact language, no phone word"},
    {"query": "the call line for MEDPLUS",
     "intent": "phone",
     "note": "'call line' instead of 'phone/mobile/telephone'"},
    {"query": "what number should I dial for SPAR",
     "intent": "phone",
     "note": "'dial' carries the intent"},
    {"query": "the hotline for FILMHOUSE",
     "intent": "phone",
     "note": "'hotline' — no 'phone/mobile/telephone'"},
    {"query": "which line do we use to reach RUBELS",
     "intent": "phone",
     "note": "'line ... reach' — contact language, no 'phone'"},
    {"query": "the number to ring for GAJI TAIWO",
     "intent": "phone",
     "note": "'ring' — colloquial call language, no pattern word"},

    # ── address ───────────────────────────────────────────────────────────
    {"query": "where is SPAR situated",
     "intent": "address",
     "note": "'situated' — patterns use address/location"},
    {"query": "the physical spot for ADDIDE",
     "intent": "address",
     "note": "'physical spot' instead of 'address/location'"},
    {"query": "which street is FILMHOUSE on",
     "intent": "address",
     "note": "'street' is a location word, absent from patterns"},
    {"query": "where are the ADDIDE branches based",
     "intent": "address",
     "note": "'branches based' — no 'address/location' word"},
    {"query": "the site of the MEDPLUS store",
     "intent": "address",
     "note": "'site' instead of 'address/location'"},
    {"query": "find out where RUBELS operates from",
     "intent": "address",
     "note": "'operates from' — location language, no pattern word"},

    # ── bank ──────────────────────────────────────────────────────────────
    {"query": "which financial institution serves MEDPLUS",
     "intent": "bank",
     "note": "'financial institution' — no 'bank' token"},
    {"query": "the banking partner of ADDIDE",
     "intent": "bank",
     "note": "'banking' is not the word-boundary pattern 'banks?'"},
    {"query": "where does SPAR keep its money",
     "intent": "bank",
     "note": "colloquial 'keeps its money'"},
    {"query": "who holds MEDPLUS' money",
     "intent": "bank",
     "note": "'holds money' — no 'bank' token"},
    {"query": "the financial house for SPAR",
     "intent": "bank",
     "note": "'financial house' — institution language, no 'bank'"},
    {"query": "which institution processes ADDIDE's cards",
     "intent": "bank",
     "note": "'processes cards' — banking language, no pattern word"},

    # ── account_name ──────────────────────────────────────────────────────
    {"query": "what name is on the account for MEDPLUS",
     "intent": "account_name",
     "note": "word order defeats 'account name'/'account holder' patterns"},
    {"query": "the holder of the account for MONEYTRUST",
     "intent": "account_name",
     "note": "'holder of the account' — pattern is 'account holder'"},
    {"query": "what title is on SPAR's account",
     "intent": "account_name",
     "note": "'title on account' — word order defeats 'account name/holder'"},
    {"query": "whose name sits on the account for ARTEE INDUSTRIES",
     "intent": "account_name",
     "note": "'name sits on' — no 'account name/holder' phrase"},

    # ── account_number ────────────────────────────────────────────────────
    {"query": "the digits of the account for MEDPLUS",
     "intent": "account_number",
     "note": "'digits' — no 'account number' phrase"},
    {"query": "the account figures for LAGOON WATERS",
     "intent": "account_number",
     "note": "'figures' is numeric language, no pattern word"},
    {"query": "the figures of the account for MONEYTRUST",
     "intent": "account_number",
     "note": "'figures of the account' — no 'account number'"},
    {"query": "read out the account string for ADDIDE",
     "intent": "account_number",
     "note": "'account string' — numeric language, no pattern word"},

    # ── payable ───────────────────────────────────────────────────────────
    {"query": "what's the payment code for ADDIDE",
     "intent": "payable",
     "note": "'payment code' — pattern is 'payable code'"},
    {"query": "the remittance code for SPAR",
     "intent": "payable",
     "note": "'remittance' is settlement language, no pattern word"},
    {"query": "the transfer reference for BOKKU MART",
     "intent": "payable",
     "note": "'transfer reference' — remittance language, no 'payable'"},
    {"query": "the payment tag for WSV VENTURES",
     "intent": "payable",
     "note": "'payment tag' — no 'payable code' phrase"},
    {"query": "what do we quote when paying ADDIDE",
     "intent": "payable",
     "note": "'quote when paying' — settlement language, no pattern word"},

    # ── alias ─────────────────────────────────────────────────────────────
    {"query": "what other names does ARTEE go by",
     "intent": "alias",
     "note": "'other names' / 'go by' — no alias/formerly pattern word"},
    {"query": "the other trading names for MEDPLUS",
     "intent": "alias",
     "note": "'trading names' instead of 'alias'"},
    {"query": "the other names ADDIDE answers to",
     "intent": "alias",
     "note": "'answers to' — no 'alias/formerly' wording"},
    {"query": "the monikers used for LAGOON WATERS",
     "intent": "alias",
     "note": "'monikers' — name-variant language, no pattern word"},
    {"query": "the brand names under ARTEE INDUSTRIES",
     "intent": "alias",
     "note": "'brand names under' — no 'alias/trading names' phrase"},

    # ── contact ───────────────────────────────────────────────────────────
    {"query": "who is the person in charge at MEDPLUS",
     "intent": "contact",
     "note": "'person in charge' — no 'contact' token"},
    {"query": "who do we call at LAGOON WATERS",
     "intent": "contact",
     "note": "'who do we call' is contact language"},
    {"query": "who is the liaison for ORIENT AFRICA",
     "intent": "contact",
     "note": "'liaison' — no 'contact' token"},
    {"query": "who should we deal with at ADDIDE",
     "intent": "contact",
     "note": "'deal with at' — contact language, no pattern word"},
    {"query": "the officer in charge at FILMHOUSE",
     "intent": "contact",
     "note": "'officer in charge' — no 'contact person' phrase"},

    # ── onboarded ─────────────────────────────────────────────────────────
    {"query": "when did MEDPLUS join the network",
     "intent": "onboarded",
     "note": "'join the network' instead of 'onboarded'"},
    {"query": "how long has SPAR been with us",
     "intent": "onboarded",
     "note": "tenure phrasing, no pattern word"},
    {"query": "since when has MEDPLUS been live",
     "intent": "onboarded",
     "note": "'been live' — no 'onboarded' word"},
    {"query": "the start date of ADDIDE's contract",
     "intent": "onboarded",
     "note": "'start date' — onboarding language, no pattern word"},
    {"query": "how long has SPAR traded with us",
     "intent": "onboarded",
     "note": "tenure phrasing — no 'onboarded' word"},

    # ── state ─────────────────────────────────────────────────────────────
    {"query": "which region is LAGOON WATERS in",
     "intent": "state",
     "note": "'region' — patterns use 'state'"},
    {"query": "which city zone is ADDIDE in",
     "intent": "state",
     "note": "'city zone' — location/state language, no pattern word"},
    {"query": "which part of the country is LAGOON WATERS in",
     "intent": "state",
     "note": "'part of the country' — no 'state' token"},
    {"query": "whereabouts is the BOKKU MART branch",
     "intent": "state",
     "note": "'whereabouts' — location language, no 'state'"},

    # ── source ────────────────────────────────────────────────────────────
    {"query": "which workbook did MEDPLUS come from",
     "intent": "source",
     "note": "'workbook' — patterns use file/sheet"},
    {"query": "the origin file for SPAR",
     "intent": "source",
     "note": "'origin file' — no 'which file'/'which sheet' wording"},
    {"query": "which upload brought ARTEE INDUSTRIES in",
     "intent": "source",
     "note": "'upload brought in' — provenance language, no 'file/sheet'"},
    {"query": "the originating spreadsheet for WSV VENTURES",
     "intent": "source",
     "note": "'originating spreadsheet' — no 'which file' wording"},
    {"query": "trace GAJI TAIWO back to its workbook",
     "intent": "source",
     "note": "'trace back to workbook' — no 'which file/sheet' phrase"},

    # ── change_details ────────────────────────────────────────────────────
    {"query": "the account history for LAGOON WATERS",
     "intent": "change_details",
     "note": "'account history' — pattern is 'change history'"},
    {"query": "what did SPAR's account used to be",
     "intent": "change_details",
     "note": "'used to be' carries the before/after meaning"},
    {"query": "have the details for ADDIDE ever changed",
     "intent": "change_details",
     "note": "'details ... changed' split across the sentence"},
    {"query": "was MEDPLUS' account ever different",
     "intent": "change_details",
     "note": "'ever different' — before/after meaning, no pattern phrase"},
    {"query": "the before and after for ADDIDE's account",
     "intent": "change_details",
     "note": "'before and after' — no 'change/old/new' pattern word"},
    {"query": "did ARTEE INDUSTRIES switch banks",
     "intent": "change_details",
     "note": "'switch banks' — account-change language, no pattern phrase"},
    {"query": "what was LAGOON WATERS' previous account",
     "intent": "change_details",
     "note": "'previous account' — no 'old account' phrase"},

    # ── profile ───────────────────────────────────────────────────────────
    {"query": "tell me all there is to know about MEDPLUS",
     "intent": "profile",
     "note": "'all there is to know about' — 'everything about' / bare 'everything' both miss"},
    {"query": "the full lowdown on SPAR",
     "intent": "profile",
     "note": "'lowdown' instead of profile/information/details"},
    {"query": "give me the complete picture of SPAR",
     "intent": "profile",
     "note": "'complete picture' — no 'profile/information/details'"},
    {"query": "what do we have on ADDIDE",
     "intent": "profile",
     "note": "'have on' — dossier language, no pattern word"},
    {"query": "the whole story of ARTEE INDUSTRIES",
     "intent": "profile",
     "note": "'whole story' — no 'profile/details' word"},

    # ── count ─────────────────────────────────────────────────────────────
    {"query": "the total tally of merchants in the NNPC file",
     "intent": "count",
     "note": "'total tally' — no 'how many'/'count'/'number of'"},
    {"query": "the sum of merchants in the MRSP file",
     "intent": "count",
     "note": "'sum' is arithmetic language, no pattern word"},
    {"query": "the tally of MEDPLUS branches in the NNPC file",
     "intent": "count",
     "note": "'tally of' — no 'how many/count/number of'"},
    {"query": "the grand total of ADDIDE outlets",
     "intent": "count",
     "note": "'grand total of' — no 'count/number of' phrase"},
    {"query": "size up the NNPC merchant list",
     "intent": "count",
     "note": "'size up' — quantification language, no pattern word"},

    # ── duplicates ────────────────────────────────────────────────────────
    {"query": "which merchants show up twice in the registry",
     "intent": "duplicates",
     "note": "'show up twice' — no 'duplicate'/'more than once'"},
    {"query": "which names are listed twice in the NNPC file",
     "intent": "duplicates",
     "note": "'listed twice' instead of 'repeated'"},
    {"query": "which MEDPLUS entries occur twice",
     "intent": "duplicates",
     "note": "'occur twice' — no 'duplicate/repeated'"},
    {"query": "any double listings of ADDIDE",
     "intent": "duplicates",
     "note": "'double listings' — no 'duplicates/repeated'"},
    {"query": "do any SPAR records overlap",
     "intent": "duplicates",
     "note": "'records overlap' — no 'duplicate/repeated' wording"},

    # ── summary ───────────────────────────────────────────────────────────
    {"query": "give me the gist of the NNPC file",
     "intent": "summary",
     "note": "'gist' — no summary/overview/breakdown word"},
    {"query": "the overall picture of the MRSP file",
     "intent": "summary",
     "note": "'overall picture' instead of 'overview'"},
    {"query": "the quick read on the NNPC file",
     "intent": "summary",
     "note": "'quick read' — no 'summary/overview/breakdown'"},
    {"query": "give me the essence of the MRSP file",
     "intent": "summary",
     "note": "'essence of' — no 'summary/stats' word"},

    # ── related ───────────────────────────────────────────────────────────
    {"query": "what else is tied to LAGOON WATERS",
     "intent": "related",
     "note": "'tied to' — pattern is 'linked to'"},
    {"query": "who shares an identity with MEDPLUS",
     "intent": "related",
     "note": "'shares an identity' — no related/connected/associated word"},
    {"query": "what shares records with MONEYTRUST",
     "intent": "related",
     "note": "'shares records with' — no 'related/linked' word"},
    {"query": "the records touching GAJI TAIWO",
     "intent": "related",
     "note": "'records touching' — no 'linked/connected' word"},
    {"query": "who overlaps with LAGOON WATERS",
     "intent": "related",
     "note": "'overlaps with' — identity language, no pattern word"},

    # ── formerly ──────────────────────────────────────────────────────────
    {"query": "what did MEDPLUS use to be called",
     "intent": "formerly",
     "note": "'used to be called' — no 'formerly'/'known as'"},
    {"query": "the old name of SPAR",
     "intent": "formerly",
     "note": "'old name' — not 'name variants'/'formerly'"},
    {"query": "what was ARTEE INDUSTRIES called before",
     "intent": "formerly",
     "note": "'called before' — no 'formerly/known as'"},
    {"query": "the earlier name of ADDIDE",
     "intent": "formerly",
     "note": "'earlier name' — no 'name variants/formerly'"},
    {"query": "has SPAR rebranded",
     "intent": "formerly",
     "note": "'rebranded' — name-change language, no pattern word"},

    # ── compare ───────────────────────────────────────────────────────────
    {"query": "how do SPAR and ADDIDE stack up",
     "intent": "compare",
     "note": "'stack up' — no compare/versus/vs wording"},
    {"query": "which is bigger between SPAR and ADDIDE",
     "intent": "compare",
     "note": "'which is bigger between' — no pattern word"},
    {"query": "how do MEDPLUS and SPAR measure up",
     "intent": "compare",
     "note": "'measure up' — no 'compare/vs' wording"},
    {"query": "lay MEDPLUS and ADDIDE next to each other",
     "intent": "compare",
     "note": "'lay next to each other' — no 'compare/versus'"},
    {"query": "which of the two is bigger, FILMHOUSE or BEACONHEALTH",
     "intent": "compare",
     "note": "'which of the two is bigger' — no pattern word"},

    # ── coverage ──────────────────────────────────────────────────────────
    {"query": "which MEDPLUS outlets are short a phone number",
     "intent": "coverage",
     "note": "'short a phone number' — no missing/without/has-no wording"},
    {"query": "which SPAR branches never gave us an email",
     "intent": "coverage",
     "note": "'never gave us' instead of 'missing'"},
    {"query": "which MEDPLUS stores are short of a phone",
     "intent": "coverage",
     "note": "'short of a phone' — no 'missing/without/has no'"},
    {"query": "the ADDIDE branches we never got an email for",
     "intent": "coverage",
     "note": "'never got ... for' — no 'missing/lacking'"},
    {"query": "which SPAR outlets lack a bank",
     "intent": "coverage",
     "note": "'lack a bank' — no 'missing/without' wording"},

    # ── top ───────────────────────────────────────────────────────────────
    {"query": "the biggest banks in the NNPC file",
     "intent": "top",
     "note": "'biggest' — pattern is 'top N'/'most common'/'ranking'"},
    {"query": "the leading states in the MRSP file",
     "intent": "top",
     "note": "'leading' instead of 'top'/'ranking'"},
    {"query": "the largest merchant families by size",
     "intent": "top",
     "note": "'largest ... by size' — no 'top N/ranking'"},
    {"query": "which banks feature most in the MRSP file",
     "intent": "top",
     "note": "'feature most' — no 'most common/top' phrase"},

    # ── verify ────────────────────────────────────────────────────────────
    {"query": "is MEDPLUS on the system",
     "intent": "verify",
     "note": "'on the system' — no 'in the registry'/'registered'"},
    {"query": "does SPAR exist in our records",
     "intent": "verify",
     "note": "'exist in our records' instead of 'verify/registered'"},
    {"query": "is MEDPLUS in the system",
     "intent": "verify",
     "note": "'in the system' — no 'registered/verify/valid'"},
    {"query": "does the parameter file have ARTEE INDUSTRIES",
     "intent": "verify",
     "note": "'does the file have' — no 'verify/registered'"},
    {"query": "can we find GAJI TAIWO in our data",
     "intent": "verify",
     "note": "'find in our data' — no 'in the registry/database'"},

    # ── settlement_account ──────────────────────────────────────────────
    {"query": "which account does the dealer settlement go to for 2103O380",
     "intent": "settlement_account",
     "note": "'dealer settlement go to' — no 'settlement account'/'dealer account' phrase"},
    {"query": "where does OLUSEGUN ADERIBIGBE receive payments",
     "intent": "settlement_account",
     "note": "'receive payments' — settlement language, no pattern word"},
    {"query": "the payout account for this NNPC dealer",
     "intent": "settlement_account",
     "note": "'payout account' — no 'settlement account'/'dealer account'"},
    {"query": "what account does this NNPC dealer settle into",
     "intent": "settlement_account",
     "note": "'settle into' — verb form, no 'settlement account'/'dealer account' noun phrase"},
    {"query": "what bank account is the dealer settled into",
     "intent": "settlement_account",
     "note": "'dealer settled into' — settlement verb, no noun phrase match"},

    # ── settlement_bank ─────────────────────────────────────────────────
    {"query": "which bank processes the dealer settlement for 2103O380",
     "intent": "settlement_bank",
     "note": "'bank processes the dealer settlement' — no 'settlement bank'/'dealer bank'"},
    {"query": "the receiving bank for this dealer's payments",
     "intent": "settlement_bank",
     "note": "'receiving bank for dealer payments' — no pattern phrase"},
    {"query": "what bank is OLUSEGUN ADERIBIGBE settled through",
     "intent": "settlement_bank",
     "note": "'settled through' — settlement verb, no noun match"},
    {"query": "which bank does this dealer route payments through",
     "intent": "settlement_bank",
     "note": "'route payments through' — settlement bank language, no pattern noun"},

    # ── merchant_id ─────────────────────────────────────────────────────
    {"query": "what internal identifier does MEDPLUS have",
     "intent": "merchant_id",
     "note": "'internal identifier' — identification language, no 'merchant id' phrase"},
    {"query": "the MERCHANTID field for 2103O380",
     "intent": "merchant_id",
     "note": "raw field name reference"},
    {"query": "the system-assigned ID for ADDIDE in the parameter file",
     "intent": "merchant_id",
     "note": "'system-assigned ID' — identification language, no 'merchant id' phrase"},
    {"query": "what ID is this merchant registered under in the system",
     "intent": "merchant_id",
     "note": "'registered under' — identification language, no 'merchant id'"},

    # ── dealer_name ─────────────────────────────────────────────────────
    {"query": "who is the dealer for 2103O380",
     "intent": "dealer_name",
     "note": "'who is the dealer' — no 'dealer name'/'trading name' phrase"},
    {"query": "what is the official name of the person running this NNPC station",
     "intent": "dealer_name",
     "note": "'person running this station' — dealer/operator language, no pattern phrase"},
    {"query": "which person operates this terminal",
     "intent": "dealer_name",
     "note": "'person operates' — dealer language, no pattern word"},
    {"query": "who is the named operator for this terminal",
     "intent": "dealer_name",
     "note": "'named operator' — dealer name language, no 'dealer name'/'trading name'"},

    # ── segment (collection requests) ─────────────────────────────────────
    {"query": "all the addresses of all nnpc stations",
     "intent": "segment",
     "note": "collective-marker phrasing; segment is injected, not regex-scored"},
    {"query": "every terminal across all NNPC locations",
     "intent": "segment",
     "note": "'every ... across all' collective phrasing"},
    {"query": "all the emails of every nnpc station",
     "intent": "segment",
     "note": "collective phrasing with a field; segment is injected, not regex-scored"},
    {"query": "give me the phone numbers of all NNPC stations",
     "intent": "segment",
     "note": "collective phrasing; segment is injected"},
    {"query": "every address in the NNPC file",
     "intent": "segment",
     "note": "collective phrasing; segment is injected"},
]


def for_intent(intent: str):
    """Every golden entry expected to resolve to `intent`."""
    return [e for e in INTENT_GOLDEN if e.get("intent") == intent]


def intents_covered() -> list:
    """Distinct expected intents in the set, in first-appearance order."""
    seen = []
    for e in INTENT_GOLDEN:
        if e["intent"] not in seen:
            seen.append(e["intent"])
    return seen
