/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#004ac6',
        'primary-container': '#2563eb',
        'on-primary': '#ffffff',
        'on-primary-container': '#00174b',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        secondary: '#006c49',
        'secondary-container': '#6cf8bb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714d',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0d1c2f',
        surface: '#f8f9ff',
        'on-surface': '#0d1c2f',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#ccdbf4',
        'surface-variant': '#d5e3fd',
        'on-surface-variant': '#434655',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dde9ff',
        'surface-container-highest': '#d5e3fd',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#ebf1ff',
        tertiary: '#784b00',
        'tertiary-container': '#996100',
        'on-tertiary': '#ffffff',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        plex: ['IBM Plex Sans', 'sans-serif'],
      },
      boxShadow: {
        sm: '0 1px 2px rgba(13,28,47,.05), 0 1px 3px rgba(13,28,47,.06)',
        md: '0 4px 12px rgba(13,28,47,.08)',
        lg: '0 8px 24px rgba(13,28,47,.10)',
      },
      keyframes: {
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        toast: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '10%, 90%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(24px)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.4s ease-out forwards',
        toast: 'toast 4s ease forwards',
      },
    },
  },
  plugins: [],
}
